mobile nav implementation
stackabletech/documentation-ui pull request #3
Opened 2022-02-24 20:48 UTC by lfrancke

2022-02-24 20:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stackabletech/documentation-ui?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stackabletech/documentation-ui?pullRequest=3) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stackabletech/documentation-ui?pullRequest=3) it.</sub>

2022-03-04 15:40 UTC, siegfriedweber requested changes
If a mobile device is rotated to landscape mode then the menu entries at the bottom are not reachable. The navigation bar is not scrollable.

2022-03-08 16:12 UTC, lfrancke commented
@dropclick Could you take a look here?

2022-03-10 21:02 UTC, dropclick commented
@siegfriedweber @lfrancke Fixed issue regarding mobile navigation being cut off and not scrollable in portrait mode. Please verify.

2022-03-18 08:07 UTC, closed without merging