added breadcrumbs - styling needs work
stackabletech/documentation-ui pull request #63
Opened 2024-07-02 09:40 UTC by fhennig

2024-07-02 11:00 UTC, fhennig commented
![image](https://github.com/stackabletech/documentation-ui/assets/5787489/de630dc6-29a4-4943-a6c8-3e978d89312c)

This is what it currently looks like

2024-07-02 15:54 UTC, fhennig commented
![image](https://github.com/stackabletech/documentation-ui/assets/5787489/07d3ce45-c258-4fbf-80b1-894f68594057)


Update

2024-07-03 07:38 UTC, Techassi approved these changes

2024-07-03 07:41 UTC, merged

2024-07-03 07:41 UTC, Techassi requested changes

2024-07-03 07:41 UTC, Techassi commented on README.adoc
> +Only the stable docs are index (no previous versions, no nightly).
typo:

```suggestion
Only the stable docs are indexed (no previous versions, no nightly).
```